apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdf-basic-service
  namespace: pdf-basic-tier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdf-basic-service
  template:
    metadata:
      labels:
        app: pdf-basic-service
        tier: basic
    spec:
      containers:
      - name: pdf-basic-service
        image: pdf-basic-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "300m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "256Mi"
        env:
        - name: TIER
          value: "basic"
        - name: MAX_FILE_SIZE
          value: "10MB"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdf-business-service
  namespace: pdf-business-tier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdf-business-service
  template:
    metadata:
      labels:
        app: pdf-business-service
        tier: business
    spec:
      containers:
      - name: pdf-business-service
        image: pdf-business-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "500m"
            memory: "1Gi"
          requests:
            cpu: "200m"
            memory: "512Mi"
        env:
        - name: TIER
          value: "business"
        - name: MAX_FILE_SIZE
          value: "50MB"
        - name: ADVANCED_FEATURES
          value: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdf-enterprise-service
  namespace: pdf-enterprise-tier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdf-enterprise-service
  template:
    metadata:
      labels:
        app: pdf-enterprise-service
        tier: enterprise
    spec:
      containers:
      - name: pdf-enterprise-service
        image: pdf-enterprise-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "800m"
            memory: "1.5Gi"
          requests:
            cpu: "300m"
            memory: "1Gi"
        env:
        - name: TIER
          value: "enterprise"
        - name: MAX_FILE_SIZE
          value: "100MB"
        - name: ADVANCED_FEATURES
          value: "true"
        - name: PREMIUM_FEATURES
          value: "true"
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pdf-basic-pdb
  namespace: pdf-basic-tier
spec:
  minAvailable: 0
  selector:
    matchLabels:
      app: pdf-basic-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pdf-business-pdb
  namespace: pdf-business-tier
spec:
  minAvailable: 0
  selector:
    matchLabels:
      app: pdf-business-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pdf-enterprise-pdb
  namespace: pdf-enterprise-tier
spec:
  minAvailable: 0
  selector:
    matchLabels:
      app: pdf-enterprise-service
