apiVersion: v1
kind: ResourceQuota
metadata:
  name: basic-tier-quota
  namespace: pdf-basic-tier
spec:
  hard:
    requests.cpu: "200m"
    requests.memory: "512Mi"
    limits.cpu: "500m"
    limits.memory: "1Gi"
    pods: "2"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: business-tier-quota
  namespace: pdf-business-tier
spec:
  hard:
    requests.cpu: "400m"
    requests.memory: "1Gi"
    limits.cpu: "1000m"
    limits.memory: "2Gi"
    pods: "3"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: enterprise-tier-quota
  namespace: pdf-enterprise-tier
spec:
  hard:
    requests.cpu: "600m"
    requests.memory: "2Gi"
    limits.cpu: "1500m"
    limits.memory: "3Gi"
    pods: "5"
