apiVersion: v1
kind: Service
metadata:
  name: pdf-basic-service
  namespace: pdf-basic-tier
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: pdf-basic-service
---
apiVersion: v1
kind: Service
metadata:
  name: pdf-business-service
  namespace: pdf-business-tier
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: pdf-business-service
---
apiVersion: v1
kind: Service
metadata:
  name: pdf-enterprise-service
  namespace: pdf-enterprise-tier
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: pdf-enterprise-service
